version: "3.9"

name: nginx_react_project

services:
  app:
    build: .

    image: react-nginx:v1

    ports:
      - "8080:80"

    restart: always

    networks:
      - reactnetwok

networks:
  reactnetwok:
    external: true
