version: "3"
name: "nginx_react_project"

Services:
 app:
   image: react-nginx:v1
   ports:
    - "3000:80"
   restart: always
   volumes:
    - "-/nginx/nginx.conf://etc/nginx/nginx.conf:ro"
    network:
      network:
        ipv4_address: *.*.*.*
network:
  network:
    driver:bridge
    ipam: 
      config:
        - subnet: ****
          gateway: ****         